version: '3'

networks:
  matrix-web:
    external: true

services:
  bot:
    image: nim65s/matrix-webhook
    build: .
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - matrix-web
    ports:
      - "127.0.0.1:${HTTP_PORT}:4785"
